apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      containers:
      - name: employee-frontend
        image: hoooo/frontend_0131
        imagePullPolicy: Always
        env:
          - name: BACKEND_API_URL
            value: "employee-backend" 
        ports:
        - containerPort: 80
