apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-front
  template:
    metadata:
      labels:
        app: canary-front
    spec:
      containers:
      - name: canary-rollouts-front
        image: ghcr.io/shclub/vue3:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
---
kind: Service
apiVersion: v1
metadata:
  name: canary-front-service
spec:
  selector:
    app: canary-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30083
  type: NodePort
