apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#  name: frontend-ingress
  name: traefik-routers
  annotations:
   kubernetes.io/ingress.class: "traefik"
#   kubernetes.io/ingressClassName: “nginx”
#   ingressclass.kubernetes.io/is-default-class: “true”
#   ingress.kubernetes.io/rewrite-target: /    
spec:
  rules:
  - host: frontend.211.43.12.162.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
